platform :ios, '7.0'
xcodeproj 'linkid-example-ios.xcodeproj'
source 'https://github.com/CocoaPods/Specs.git'

target "linkid-example-ios" do

  #pod 'LinkIDSDK', :git => 'https://github.com/link-nv/linkid-sdk-ios.git'
  pod 'LinkIDSDK',               '1.0.5'
  pod 'MBProgressHUD',           '0.9.2'
  pod 'UIActionSheet+Blocks',    '0.9'
  pod 'AFNetworkActivityLogger', '2.0.4'

end