platform :ios, '6.0'

#pod 'LinkIDSDK', :git => 'https://github.com/link-nv/linkid-sdk-ios.git'
pod 'LinkIDSDK',             '~> 0.0.1'
pod 'MBProgressHUD',         '~> 0.8'
pod "RestKit",               '~> 0.20.3'
pod 'UIActionSheet+Blocks',  '~> 0.8'
